source("data_io.R")
source("contagion_model.R")
source("data_selection.R")
source("plots.R")
source("optional_arguments_management.R")
source("displayer.R")
source("data_manipulation.R")
source("goodness_of_fit.R")
source("data_formatting.R")

update_data()